# Generated by Django 4.1.4 on 2023-01-08 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participantsanswers_answer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsanswers',
            name='question',
        ),
        migrations.AddField(
            model_name='participantsanswers',
            name='question_id',
            field=models.PositiveIntegerField(default=1, verbose_name='ID вопроса'),
        ),
        migrations.AlterField(
            model_name='participantsanswers',
            name='answer_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID ответа'),
        ),
        migrations.AlterField(
            model_name='participantsanswers',
            name='session',
            field=models.PositiveIntegerField(default=1, verbose_name='ID сессии'),
        ),
        migrations.AlterField(
            model_name='participantsanswers',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 15, 32, 56, 477196), verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 15, 32, 56, 477196), verbose_name='Время окончания прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_olympic',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 15, 32, 56, 477196), verbose_name='Время начала прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_startpage',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 15, 32, 56, 477196), verbose_name='Время входа в АИС'),
        ),
    ]
