# Generated by Django 4.1.4 on 2023-01-08 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_remove_participantsanswers_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsanswers',
            name='seq_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='participantsanswers',
            name='answer',
            field=models.CharField(default='', max_length=500, verbose_name='Ответ участника'),
        ),
        migrations.AlterField(
            model_name='participantsanswers',
            name='answer_detailed',
            field=models.TextField(default='', max_length=30000, verbose_name='Ответ участника на вопрос типа "Развернутый ответ"'),
        ),
        migrations.AlterField(
            model_name='participantsanswers',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 17, 59, 27, 338636), verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 17, 59, 27, 338636), verbose_name='Время окончания прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_olympic',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 17, 59, 27, 338636), verbose_name='Время начала прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_startpage',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 17, 59, 27, 338636), verbose_name='Время входа в АИС'),
        ),
    ]
