# Generated by Django 4.0.3 on 2023-01-10 01:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participantsanswers_time_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsanswers',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 9, 18, 3, 39545), verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 9, 18, 3, 39545), verbose_name='Время окончания прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_olympic',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 9, 18, 3, 39545), verbose_name='Время начала прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_startpage',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 9, 18, 3, 39545), verbose_name='Время входа в АИС'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
