# Generated by Django 4.0.3 on 2023-01-11 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_alter_participantsanswers_time_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsanswers',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 9, 34, 23, 332139), verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 9, 34, 23, 331140), verbose_name='Время окончания прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_olympic',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 9, 34, 23, 331140), verbose_name='Время начала прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_startpage',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 9, 34, 23, 331140), verbose_name='Время входа в АИС'),
        ),
    ]
