# Generated by Django 4.0.3 on 2023-01-13 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_alter_participantsanswers_time_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='time_stop',
            field=models.PositiveIntegerField(default=0, verbose_name='Оставшееся время выполнения олимпиады (в случае дисконнекта)'),
        ),
        migrations.AlterField(
            model_name='participantsanswers',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 19, 31, 322815), verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 19, 31, 322815), verbose_name='Время окончания прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_olympic',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 19, 31, 322815), verbose_name='Время начала прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_startpage',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 19, 31, 322815), verbose_name='Время входа в АИС'),
        ),
    ]
