# Generated by Django 4.0.3 on 2023-01-13 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_sessions_time_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsanswers',
            name='time_answer',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 42, 27, 641303), verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 42, 27, 641303), verbose_name='Время окончания прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_olympic',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 42, 27, 641303), verbose_name='Время начала прохождения олимпиады'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='time_startpage',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 9, 42, 27, 641303), verbose_name='Время входа в АИС'),
        ),
    ]
