version: '3.7'

services:
  drf:
    container_name: olympic-back
    build:
      context: ./olympiad
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./olympiad/.env
    depends_on:
      - db
    volumes:
      - olympic_media_volume:/home/drf/backend/media
      - olympic_static_volume:/home/drf/backend/static
  db:
    container_name: olympic-db
    image: postgres:14.0-alpine
    volumes:
      - olympic_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./olympiad/.env.db
    ports:
      - 5432:5432
  front:
    container_name: olympic-front
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=***backend_url***
    volumes:
      - olympic_vue_dist:/front/dist
  nginx:
    container_name: olympic-nginx
    build: ./nginx
    ports:
      - 1313:80
    volumes:
      - olympic_media_volume:/home/drf/backend/media
      - olympic_static_volume:/home/drf/backend/static
      - olympic_vue_dist:/front/dist
    depends_on:
      - drf

volumes:
  olympic_postgres_data:
  olympic_media_volume:
  olympic_static_volume:
  olympic_vue_dist:
