# Generated by Django 4.1.4 on 2022-12-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=150, unique=True, verbose_name='Наименование уровня')),
            ],
            options={
                'verbose_name': 'Уровень вопросов',
                'verbose_name_plural': 'Уровени вопросов',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.questionlevels', verbose_name='Уровень вопроса'),
        ),
    ]
