# Generated by Django 4.1.4 on 2022-12-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_questionlevels_questions_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=350, verbose_name='Наименование столбца')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Столбец ответа к вопросу',
                'verbose_name_plural': 'Столбцы ответов к вопросам',
            },
        ),
        migrations.CreateModel(
            name='QuestionPossibleValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=350, verbose_name='Возможный вариант ответа')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Возможный вариант ответа',
                'verbose_name_plural': 'Возможные варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Ответ:', max_length=350, verbose_name='Подпись к варианту ответа')),
                ('cl_correct', models.CharField(max_length=350, verbose_name='Правильный вариант ответа (тип вопроса - классический)')),
                ('check_detail', models.BooleanField(default=False, verbose_name='Проверка на тип вопроса "Развернутый ответ"')),
                ('check_table', models.BooleanField(default=False, verbose_name='Провекра на тип вопроса "Табличный"')),
                ('acc_correct', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.questionpossiblevalues', verbose_name='Правильный вариант ответа (тип вороса - соответствие)')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ к вопросу',
                'verbose_name_plural': 'Ответы к вопросам',
            },
        ),
        migrations.CreateModel(
            name='TableAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.CharField(default='Ответ', max_length=350, verbose_name='Правильный ответ')),
                ('answer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.answers', verbose_name='Ответ к вопросу')),
                ('column', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.questioncolumns', verbose_name='Столбец')),
            ],
            options={
                'verbose_name': 'Ответ к табличному типу вопроса',
                'verbose_name_plural': 'Ответы к табличному типу вопроса',
                'unique_together': {('answer_id', 'column_id')},
            },
        ),
    ]
