# Generated by Django 4.1.4 on 2022-12-31 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_questionlevels_date_create_olympiads'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='date_create',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата добавления уровня'),
        ),
    ]
