# Generated by Django 4.1.4 on 2023-01-01 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_questions_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('Развернутый', 'Развернутый'), ('Соответствие', 'Соответствие'), ('Развернутый', 'Табличный'), ('Классический', 'Классический')], default='Классическкий', max_length=50, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date_create',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата добавления вопроса'),
        ),
    ]
