# Generated by Django 4.1.4 on 2023-01-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_questions_type_alter_questions_date_create'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tableanswers',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tableanswers',
            name='label',
            field=models.CharField(default='Лэйбл', max_length=350, verbose_name='Подпись к строке ответов'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('Развернутый ответ', 'Развернутый ответ'), ('Краткий ответ', 'Краткий ответ'), ('Соответствие', 'Соответствие'), ('Табличный', 'Табличный'), ('Классический', 'Классический')], default='Классическкий', max_length=50, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='tableanswers',
            name='column',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.questioncolumns', verbose_name='Столбец'),
        ),
        migrations.RemoveField(
            model_name='tableanswers',
            name='answer',
        ),
    ]
