# Generated by Django 4.1.4 on 2023-01-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_tableanswers_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='check_detail',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='check_table',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='cl_correct',
        ),
        migrations.AddField(
            model_name='answers',
            name='short_correct',
            field=models.CharField(default='Ответ', max_length=350, verbose_name='Правильный вариант ответа (тип вопроса - краткий ответ)'),
        ),
    ]
