# Generated by Django 4.1.4 on 2023-01-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_answers_check_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicesAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='Ответ:', max_length=350, verbose_name='Вариант ответа')),
                ('correct', models.BooleanField(default=False, verbose_name='Праваильный ответ')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
