# Generated by Django 4.1.4 on 2023-01-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_choicesanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='acc_correct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.questionpossiblevalues', verbose_name='Правильный вариант ответа (тип вопроса - соответствие)'),
        ),
    ]
