# Generated by Django 4.1.4 on 2023-01-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_answers_acc_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiads',
            name='q_levels',
            field=models.ManyToManyField(null=True, to='service.questionlevels', verbose_name='Уровни вопросов'),
        ),
    ]
