# Generated by Django 4.1.4 on 2023-01-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_olympiads_q_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadsLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_number', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('olympiad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.olympiads', verbose_name='Олимпиада')),
            ],
            options={
                'verbose_name': 'Распределение уровня вопросов на олимпиаде',
                'verbose_name_plural': 'Распределения уровней вопросов на олимпиадах',
            },
        ),
    ]
