# Generated by Django 4.1.4 on 2023-01-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_olympiads_q_levels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='olympiadslevels',
            unique_together={('olympiad', 'seq_number')},
        ),
    ]
