# Generated by Django 4.1.4 on 2023-01-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_olympiadslevels_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadslevels',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.questionlevels', verbose_name='Уровень вопроса'),
        ),
    ]
