# Generated by Django 4.1.4 on 2023-01-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_olympiadslevels_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiads',
            name='time_complete',
            field=models.PositiveIntegerField(default=10, verbose_name='Время выполнения олимпиады (в минутах)'),
        ),
    ]
