# Generated by Django 4.1.4 on 2023-01-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_olympiads_time_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncolumns',
            name='seq_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Последовательный номер'),
        ),
        migrations.AddField(
            model_name='tableanswers',
            name='seq_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Последовательный номер'),
        ),
    ]
