# Generated by Django 4.0.3 on 2023-01-11 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_resultsquestions_resultssessions_delete_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsquestions',
            name='answer_correct',
        ),
        migrations.AlterField(
            model_name='resultssessions',
            name='participant_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 14, 2, 9, 286249), verbose_name='Время окончания прохождения олимпиады участником'),
        ),
        migrations.AlterField(
            model_name='resultssessions',
            name='participant_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 14, 2, 9, 286249), verbose_name='Время начала прохождения олимпиады участником'),
        ),
    ]
