# Generated by Django 4.0.3 on 2023-01-13 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_alter_resultssessions_participant_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultssessions',
            name='participant_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 12, 36, 52, 393080), verbose_name='Время окончания прохождения олимпиады участником'),
        ),
        migrations.AlterField(
            model_name='resultssessions',
            name='participant_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 12, 36, 52, 393080), verbose_name='Время начала прохождения олимпиады участником'),
        ),
    ]
