# Generated by Django 4.1.4 on 2022-12-23 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='Фамилия', max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(default='Имя', max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='Отчество', max_length=150, verbose_name='Отчество')),
                ('oo_fullname', models.TextField(default='Образовательное учреждение', max_length=500, verbose_name='Полное наименование образовательного учреждения')),
                ('oo_address', models.TextField(default='Адрес', max_length=750, verbose_name='Физический адрес образовательного учреждения')),
                ('position', models.CharField(default='Должность', max_length=150, verbose_name='Должность')),
                ('phone', models.CharField(default='+7 (000) 000-00-00', max_length=20, verbose_name='Контактный телефон')),
                ('dj_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('surname', models.CharField(default='Фамилия', max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(default='Имя', max_length=150, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('study_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Год обучения')),
                ('study_kind', models.CharField(choices=[('Предпрофессиональная', 'Предпрофессиональная'), ('Общеразвивающая', 'Общеразвивающая')], max_length=50, verbose_name='Вид обучения')),
                ('study_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)], verbose_name='Срок реализации программы обучения')),
                ('teacher', models.CharField(default='ФИО преподавателя', max_length=500, verbose_name='ФИО преподавателя')),
                ('group', models.CharField(default='Учебная группа', max_length=150, verbose_name='Группа')),
                ('identifier', models.CharField(max_length=10, unique=True, verbose_name='Идентификатор')),
                ('contact_person', models.ForeignKey(default='*Удаленный пользователь*', on_delete=django.db.models.deletion.PROTECT, to='users.profiles', verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
